### PR TITLE
Backport/pr30

### PR DESCRIPTION
**Pull request by jordansissel**
Backport #30 to plugin-api-v1

### CODE REVIEW

**Comment by jordansissel** [comment]
This is blocked due to test failures until https://github.com/elastic/logstash/issues/5273 is resolved.

**Comment by ph** [comment]
@jordansissel The PR now pick the correct gems, but the build fails because this PR uses the `Event#get` method.

**Comment by jordansissel** [comment]
@ph confirmed that the `plugin-api-v1` branch passes specps after doing a `bundle update`. :heart:

**Comment by jordansissel** [comment]
Tests pass for me. Waiting on travis.

**Comment by jordansissel** [comment]
Hurray tests pass on Travis, too.

**Comment by ph** [comment]
LGTM test passes

**Comment by jordansissel** [comment]
Merged into plugin-api-v1

**Pull request closed without merging**
