### PR TITLE
Added skip_header feature with test

### PR DESCRIPTION
**Pull request by AbdulHaseebHussain**
Added skip_header feature in reference to "Skip header option within csv filter #58" issue.

### CODE REVIEW

**Comment by guyboertje** [comment]
@AbdulHaseebHussain Thanks.

Its great that you updated the asciidoc in this PR - I forgot to ask you to do the same for the previous PR 😞 .

**Comment by guyboertje** [comment]
@AbdulHaseebHussain 
I'm a bit concerned about this `skip_header` setting - particularly about the specific documentation and how it does and does not relate to `autodetect_column_names`.

1. Document - if `skip_header` is set without `autodetect_column_names` being set then `columns` should be set and therefore any row that has exactly the same values as the specified `columns` will be skipped.
2. Document - If the two settings are both specified then `columns` should not be specified.
3. Document - If the two settings are both specified then the `autodetect_column_names` will fill the columns setting in the background, from the first event seen, and any subsequent values the match what was autodetected will be skipped.

You need to rebase this onto your previous work in master because values nil check code should appear after the skip_header section.

We do not have to bump the version number - just edit the changelog and add this change to it.

Thanks for this, its much appreciated.

**Comment by AbdulHaseebHussain** [comment]
Could you maybe review some of my other pull requests to various logstash plugins if you find the time.

**Comment by AbdulHaseebHussain** [comment]
I used pull instead of rebase, I'm still somewhat new to git, it seems everything is jumbled up now.

**Comment by AbdulHaseebHussain** [comment]
I've redone all changes on a separate branch https://github.com/logstash-plugins/logstash-filter-csv/pull/63

**Comment by guyboertje** [comment]
Closing - moving discussion to https://github.com/logstash-plugins/logstash-filter-csv/pull/59

**Pull request closed without merging**
